apiVersion: delivery.ocm.software/v1alpha1
kind: ComponentVersion
metadata:
  name: ocm-hello-world-ingress-nginx
  namespace: ocm-system
spec:
  component: ocm.software/ingress-nginx
  interval: 10s
  references:
    expand: true
  repository:
    url: ghcr.io/stb1337/ocm-hello-world
    secretRef:
      name: pull-secret
  version:
    semver: "1.10.0"
---
# resource.yaml
apiVersion: delivery.ocm.software/v1alpha1
kind: Resource
metadata:
  name: ocm-hello-world-nginx-helm-chart-external
  namespace: ocm-system
spec:
  interval: 10s
  sourceRef:
    apiVersion: delivery.ocm.software/v1alpha1
    kind: ComponentVersion
    name: ocm-hello-world-ingress-nginx
    namespace: ocm-system
    resourceRef:
      name: helm-chart-external
      version: "4.10.0"
      extraIdentity:
        helmChart: ingress-nginx # name of the chart
---
# deployer.yaml
apiVersion: delivery.ocm.software/v1alpha1
kind: FluxDeployer
metadata:
  name: ocm-hello-world-nginx-helm-chart-external
  namespace: ocm-system
spec:
  interval: 10s
  sourceRef:
    apiVersion: delivery.ocm.software/v1alpha1
    kind: Resource
    name: ocm-hello-world-nginx-helm-chart-external
  helmReleaseTemplate:
    chart: 
      spec: 
        chart: "ingress-nginx"
        interval: 10s
    values:
      fullnameOverride: ingress-nginx
      controller:
        ingressClassResource:
          default: true
        watchIngressWithoutClass: true
        config:
          # @url: https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#enable-underscores-in-headers
          enable-underscores-in-headers: "true"
        extraArgs:
          # K8_NAMESPACE/K8_SECRET_NAME
          # @url:
          # https://kubernetes.github.io/ingress-nginx/user-guide/tls/#default-ssl-certificate
          default-ssl-certificate: "default/www-tls"
        service:
          # azure specific configuration because of
          # https://github.tools.sap/kubernetes-canary/issues-canary/issues/2868
          # Works fine on GCP/AWS
          appProtocol: false
          annotations:
            # Let Gardener manage external DNS records for this Service.
            # @url:
            # https://pages.github.tools.sap/kubernetes/gardener/docs/guides/managed-dns/
            # @url:
            # https://github.com/gardener/external-dns-management#dnsannotation-objects
            cert.gardener.cloud/secretname: "www-tls"
            dns.gardener.cloud/dnsnames: "*.ocm-hello-world.ketos.shoot.canary.k8s-hana.ondemand.com"
            dns.gardener.cloud/ttl: "600"
            dns.gardener.cloud/class: "garden"
        metrics:
          # @url: https://kubernetes.github.io/ingress-nginx/user-guide/monitoring/
          enabled: true
        # @url: https://kubernetes.github.io/ingress-nginx/user-guide/monitoring/
        #podAnnotations: 
      defaultBackend:
        enabled: true
    interval: 10s
    releaseName: "nginx-helm-chart-external"
    targetNamespace: default    